In [1]:
import numpy as np

In [62]:
# true coefs
beta_true = np.array([1.6, -.9])
# generate data
np.random.seed(6)
n = 10
X = np.random.uniform(low = -5, high=5, size=(n, 2))
sigma2 = 1
y = np.random.normal(loc=X@beta_true, scale=sigma2)

In [63]:
# prior density
m_0 = np.array([0, 0])
# shrinkage factor
s = 1
S_0 = s * np.array([[1, 0], [0, 1]])
# posterior calculation
S_N = np.linalg.inv((X.T @ X) / sigma2  + np.linalg.inv(S_0))
# does likelihood noise enter in?
m_N = S_N @ ((X.T @ y) / sigma2)
m_N

array([ 1.47440808, -0.94684386])

In [24]:
beta_true

array([ 1.6, -0.9])

In [23]:
mu

array([ 1.55384057, -0.74175461])

In [15]:
tau

array([[0.01548414, 0.00171859],
       [0.00171859, 0.02038096]])

In [75]:
# N    = 200
# xlim = 10
# ylim = 10
# X    = np.linspace(-xlim, xlim, N)
# Y    = np.linspace(-ylim, ylim, N)
# X, Y = np.meshgrid(X, Y)
# pos  = np.dstack((X, Y))
# Z    = prior.pdf(pos)

# plt.figure(figsize=(5,5))
# plt.contour(X, Y, Z)
# plt.show()

In [98]:
# likelihood
# random_state = 8
# n = 3
# np.random.seed(random_state)
# mu = prior.rvs(1)
# Sigma = [[1, 1], [1, 4]]
# likelihood = multivariate_normal(mu, Sigma)
# x = likelihood.rvs(size=n)
# print(mu)
# print(x.mean(0))

[0.27361415 3.2738482 ]
[0.62948345 1.34872099]


In [99]:
labda_0 = np.linalg.inv(Sigma_0)
labda = 1 / sigma

tau = np.linalg.inv(labda_0 + n * labda)
nu = tau @ (labda_0 @ mu_0 + n * labda @ x.mean(0))
print(nu)

[0.56570032 1.15644408]
